# Chapter_2_Group_Exercise_2_Regression_Analysis_and_Feature_Selection

Group Members:

1. Arya Shinde – Matriculation Number: 100006646
2. Mirang Bhandari – Matriculation Number: 100007049
3. Yash Annapure – Matriculation Number: 100006547
4. Anushka Sawant – Matriculation Number: 100006644

# Regression Analysis and Feature Selection

Perform regression analysis on a dataset with over 1000 data points and at least 30 features. Apply preprocessing, build models, evaluate performance, and enhance them using feature selection methods. Demonstrate creativity with additional techniques or insights.

### 1. Preprocessing
- 1. Handle missing values ​​and outliers.
- 2. Scale features using standardization or normalization.
- 3. Perform feature selection.
### 2. Build and Evaluate Models
- 1. Train a Linear Regression model.
- 2.  Evaluate using R² Score and RMSE.
- 3. Perform K-Fold Cross-Validation (eg, 5-fold).
### 3. Enhance the Model
- 1. Experiment with feature selection techniques and analyze their impact.
- 2. Visualize results (eg, feature importance, residual plots).
### 4. Creativity
- 1. Try advanced models (eg, Ridge, Lasso, Polynomial).
- 2. Create insightful visualizations or optimize hyperparameters.
- 3. Put the nice text justification on your shared colab

# Step 1: Source the dataset and handle missing values
The House Prices dataset contains 1,460 residential property records from Ames, Iowa, with 40+ features describing various aspects of each home and a target variable SalePrice indicating the property's sale price. The features encompass a wide range of property characteristics including physical attributes (lot size, square footage, number of rooms, bathrooms), quality ratings (overall quality, condition, kitchen quality), structural details (foundation type, roof style, exterior materials), amenities (garage, basement, fireplace, pool), and temporal information (year built, year remodeled, year sold). 
The dataset presents typical real-world challenges including missing data, outliers, mixed data types, and multicollinearity, requiring thorough preprocessing and feature engineering for optimal model performance.

In [9]:
import pandas as pd

df = pd.read_excel("../Dataset/housing-prices.xlsx")
df.head(20)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,Fireplaces,GarageType,GarageCars,GarageArea,WoodDeckSF,PoolArea,Fence,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,Attchd,2,548,0,0,NaN,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,1,Attchd,2,460,298,0,NaN,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,1,Attchd,2,608,0,0,NaN,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,1,Detchd,3,642,0,0,NaN,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,1,Attchd,3,836,192,0,NaN,WD,Normal,250000
5,6,50,RL,85.0,14115,Pave,NaN,IR1,Lvl,AllPub,...,0,Attchd,2,480,40,0,MnPrv,WD,Normal,143000
6,7,20,RL,75.0,10084,Pave,NaN,Reg,Lvl,AllPub,...,1,Attchd,2,636,255,0,NaN,WD,Normal,307000
7,8,60,RL,NaN,10382,Pave,NaN,IR1,Lvl,AllPub,...,2,Attchd,2,484,235,0,NaN,WD,Normal,200000
8,9,50,RM,51.0,6120,Pave,NaN,Reg,Lvl,AllPub,...,2,Detchd,2,468,90,0,NaN,WD,Abnorml,129900
9,10,190,RL,50.0,7420,Pave,NaN,Reg,Lvl,AllPub,...,2,Attchd,1,205,0,0,NaN,WD,Normal,118000
10,11,20,RL,70.0,11200,Pave,NaN,Reg,Lvl,AllPub,...,0,Detchd,1,384,0,0,NaN,WD,Normal,129500
11,12,60,RL,85.0,11924,Pave,NaN,IR1,Lvl,AllPub,...,2,BuiltIn,3,736,147,0,NaN,New,Partial,345000
12,13,20,RL,NaN,12968,Pave,NaN,IR2,Lvl,AllPub,...,0,Detchd,1,352,140,0,NaN,WD,Normal,144000
13,14,20,RL,91.0,10652,Pave,NaN,IR1,Lvl,AllPub,...,1,Attchd,3,840,160,0,NaN,New,Partial,279500
14,15,20,RL,NaN,10920,Pave,NaN,IR1,Lvl,AllPub,...,1,Attchd,1,352,0,0,GdWo,WD,Normal,157000
15,16,45,RM,51.0,6120,Pave,NaN,Reg,Lvl,AllPub,...,0,Detchd,2,576,48,0,GdPrv,WD,Normal,132000
16,17,20,RL,NaN,11241,Pave,NaN,IR1,Lvl,AllPub,...,1,Attchd,2,480,0,0,NaN,WD,Normal,149000
17,18,90,RL,72.0,10791,Pave,NaN,Reg,Lvl,AllPub,...,0,CarPort,2,516,0,0,NaN,WD,Normal,90000
18,19,20,RL,66.0,13695,Pave,NaN,Reg,Lvl,AllPub,...,0,Detchd,2,576,0,0,NaN,WD,Normal,159000
19,20,20,RL,70.0,7560,Pave,NaN,Reg,Lvl,AllPub,...,0,Attchd,1,294,0,0,MnPrv,COD,Abnorml,139000

In [10]:
df.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,TotalBsmtSF,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,TotRmsAbvGrd,Fireplaces,GarageCars,GarageArea,WoodDeckSF,PoolArea,SalePrice
count,1460.000000,1460.000000,1201.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,730.500000,56.897260,70.049958,10516.828082,6.099315,5.575342,1971.267808,1984.865753,1057.429452,1.565068,0.382877,2.866438,1.046575,6.517808,0.613014,1.767123,472.980137,94.244521,2.758904,180921.195890
std,421.610009,42.300571,24.284752,9981.264932,1.382997,1.112799,30.202904,20.645407,438.705324,0.550916,0.502885,0.815778,0.220338,1.625393,0.644666,0.747315,213.804841,125.338794,40.177307,79442.502883
min,1.000000,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,34900.000000
25%,365.750000,20.000000,59.000000,7553.500000,5.000000,5.000000,1954.000000,1967.000000,795.750000,1.000000,0.000000,2.000000,1.000000,5.000000,0.000000,1.000000,334.500000,0.000000,0.000000,129975.000000
50%,730.500000,50.000000,69.000000,9478.500000,6.000000,5.000000,1973.000000,1994.000000,991.500000,2.000000,0.000000,3.000000,1.000000,6.000000,1.000000,2.000000,480.000000,0.000000,0.000000,163000.000000
75%,1095.250000,70.000000,80.000000,11601.500000,7.000000,6.000000,2000.000000,2004.000000,1298.250000,2.000000,1.000000,3.000000,1.000000,7.000000,1.000000,2.000000,576.000000,168.000000,0.000000,214000.000000
max,1460.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,6110.000000,3.000000,2.000000,8.000000,3.000000,14.000000,3.000000,4.000000,1418.000000,857.000000,738.000000,755000.000000

In [24]:
y = df['SalePrice']
X = df.drop(['SalePrice', 'Id'], axis=1)

## Step 1.1: Check Missing Values and sum them up

In [26]:
X = X.drop(['Fence'], axis=1)

In [27]:
miss = pd.DataFrame((X.isnull().sum()))
display(miss)

               0
MSSubClass     0
MSZoning       0
LotFrontage    0
LotArea        0
Street         0
Alley          0
LotShape       0
LandContour    0
Utilities      0
LotConfig      0
LandSlope      0
Neighborhood   0
Condition1     0
Condition2     0
BldgType       0
HouseStyle     0
OverallQual    0
OverallCond    0
YearBuilt      0
YearRemodAdd   0
RoofStyle      0
RoofMatl       0
Exterior1st    0
Exterior2nd    0
Foundation     0
TotalBsmtSF    0
HeatingQC      0
CentralAir     0
Electrical     0
FullBath       0
HalfBath       0
BedroomAbvGr   0
KitchenAbvGr   0
KitchenQual    0
TotRmsAbvGrd   0
Functional     0
Fireplaces     0
GarageType     0
GarageCars     0
GarageArea     0
WoodDeckSF     0
PoolArea       0
SaleType       0
SaleCondition  0

## Step 1.2: Handle Missing Values
Only 'LotFrontage' contains missing values out of numerical columns. So we will be using median imputation. Median imputation is used to handle missing values in the total_bedrooms feature, as it is robust to outliers and preserves the original distribution better than mean imputation.

'Electrical', 'GarageType', 'Alley' are the categorical columns with missing values. We choose to replace them with their mode (most frequent) value.

In [28]:
# Numerical Missing Column
X = X.fillna(df['LotFrontage'].median())

In [59]:
# Fill categorical missing with mode
X['Electrical'] = X['Electrical'].fillna(X['Electrical'].mode()[0])
X['GarageType'] = X['GarageType'].fillna(X['GarageType'].mode()[0])
X['Alley'] = X['Alley'].fillna(X['Alley'].mode()[0])

In [30]:
X.isnull().sum()

MSSubClass       0
MSZoning         0
LotFrontage      0
LotArea          0
Street           0
Alley            0
LotShape         0
LandContour      0
Utilities        0
LotConfig        0
LandSlope        0
Neighborhood     0
Condition1       0
Condition2       0
BldgType         0
HouseStyle       0
OverallQual      0
OverallCond      0
YearBuilt        0
YearRemodAdd     0
RoofStyle        0
RoofMatl         0
Exterior1st      0
Exterior2nd      0
Foundation       0
TotalBsmtSF      0
HeatingQC        0
CentralAir       0
Electrical       0
FullBath         0
HalfBath         0
BedroomAbvGr     0
KitchenAbvGr     0
KitchenQual      0
TotRmsAbvGrd     0
Functional       0
Fireplaces       0
GarageType       0
GarageCars       0
GarageArea       0
WoodDeckSF       0
PoolArea         0
SaleType         0
SaleCondition    0
dtype: int64

## Step 1.3: Handle Outliers

In [50]:
numeric_cols = X.select_dtypes(include=[np.number]).columns

outlier_summary = {}
for col in numeric_cols:
    Q1 = X[col].quantile(0.25)
    Q3 = X[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    
    outlier_count = ((X[col] < lower) | (X[col] > upper)).sum()
    if outlier_count > 0:
        outlier_summary[col] = outlier_count

print("\n=== Outliers in All Numeric Columns ===")
for col, count in sorted(outlier_summary.items(), key=lambda x: x[1], reverse=True)[:10]:
    print(f"{col}: {count}")

=== Outliers in All Numeric Columns ===
RoofStyle: 319
MSZoning: 309
SaleCondition: 262
BldgType: 240
Condition1: 200
SaleType: 193
LandContour: 149
Electrical: 126
KitchenQual: 100
Functional: 100

The following columns have outliers: ['RoofStyle', 'MSZoning', 'SaleCondition', 'BldgType', 'Condition1', 'SaleType', 'LandContour', 'Electrical', 'KitchenQual', 'Functional']
We will doing log transformation to handle these outliers since log transformation reduces skewness and minimizes the impact of extreme values while retaining all observations.

In [ ]:
outlier_cols = ['RoofStyle', 'MSZoning', 'SaleCondition', 'BldgType', 
                'Condition1', 'SaleType', 'LandContour', 'Electrical', 
                'KitchenQual', 'Functional']

for col in outlier_cols:
    X[col] = np.log1p(X[col])

print(f"Columns transformed: {len(outlier_cols)}")

Log transformation applied!
Columns transformed: 10

Outliers after log transformation:
RoofStyle: 0
MSZoning: 0
SaleCondition: 0
BldgType: 0
Condition1: 0
SaleType: 0
LandContour: 0
Electrical: 0
KitchenQual: 100
Functional: 0

# Step 2: Feature Scaling

In [57]:
import numpy as np
from sklearn.preprocessing import StandardScaler, LabelEncoder

numerical_cols = X.select_dtypes(include=[np.number]).columns.tolist()

scaler = StandardScaler()
X[numerical_cols] = scaler.fit_transform(X[numerical_cols])

## Step 2.1 Encode Categorical Variable

In [37]:
categorical_cols = X.select_dtypes(include=['object']).columns.tolist()

for col in categorical_cols:
    le = LabelEncoder()
    X[col] = le.fit_transform(X[col].astype(str))

In [58]:
print(f"Numerical features scaled: {len(numerical_cols)}")
print(f"Shape: {X.shape}")

Numerical features scaled: 44
Shape: (1460, 44)

## Step 2.2: Standardization
Standardization ensures that all numerical features are on the same scale, which improves convergence and performance of regression models.

In [39]:
from sklearn.preprocessing import MinMaxScaler

normalizer = MinMaxScaler()
X[numerical_cols] = normalizer.fit_transform(X[numerical_cols])

# Step 3: Feature Selection

## Step 3.1: Correlation-Based Feature Selection

In [60]:
correlation_matrix = X.corrwith(y).abs().sort_values(ascending=False)

# Select features with correlation > 0.3
selected_corr = correlation_matrix[correlation_matrix > 0.3].index.tolist()

print(f"Correlation-based: {len(selected_corr)} features selected")
print(f"Features: {selected_corr[:15]}")

X_corr = X[selected_corr]

Correlation-based: 15 features selected
Features: ['OverallQual', 'GarageCars', 'TotalBsmtSF', 'GarageArea', 'KitchenQual', 'FullBath', 'TotRmsAbvGrd', 'YearBuilt', 'YearRemodAdd', 'Fireplaces', 'LotArea', 'HeatingQC', 'Foundation', 'LotFrontage', 'WoodDeckSF']

C:\Users\Anushka\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\numpy\lib\_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Users\Anushka\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\numpy\lib\_function_base_impl.py:3066: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

Features with low correlation to the target variable are unlikely to contribute significantly to predictive performance and can introduce noise. So we select 15 features from this method like 'OverallQual', 'GarageCars', 'TotalBsmtSF', 'GarageArea', 'KitchenQual', 'FullBath', 'TotRmsAbvGrd', 'YearBuilt', 'YearRemodAdd', 'Fireplaces', 'LotArea', 'HeatingQC', 'Foundation', 'LotFrontage', 'WoodDeckSF'

## Step 3.2: Lasso (L1 Regularization)

In [46]:
from sklearn.linear_model import Lasso
from sklearn.feature_selection import SelectFromModel
lasso = Lasso(alpha=100, random_state=42)
lasso.fit(X, y)

# Get features with non-zero coefficients
lasso_coef = pd.Series(lasso.coef_, index=X.columns)
selected_lasso = lasso_coef[lasso_coef != 0].index.tolist()

print(f"\nLasso-based: {len(selected_lasso)} features selected")
print(f"Features: {selected_lasso}")

X_lasso = X[selected_lasso]

Lasso-based: 36 features selected
Features: ['MSZoning', 'LotArea', 'Alley', 'LotShape', 'LandContour', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'Foundation', 'TotalBsmtSF', 'HeatingQC', 'Electrical', 'FullBath', 'HalfBath', 'BedroomAbvGr', 'KitchenQual', 'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'GarageType', 'GarageCars', 'GarageArea', 'WoodDeckSF', 'SaleType', 'SaleCondition']

Lasso regression performs embedded feature selection by shrinking less important feature coefficients to zero, resulting in a simpler and more interpretable model. As a result of which 36 features are selected with Lasso.

## Step 3.3: Recursive Feature Elimination (RFE)

In [47]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LinearRegression

estimator = LinearRegression()
rfe = RFE(estimator, n_features_to_select=30)
rfe.fit(X, y)

selected_rfe = X.columns[rfe.support_].tolist()

print(f"\nRFE-based: {len(selected_rfe)} features selected")
print(f"Features: {selected_rfe}")

X_rfe = X[selected_rfe]

RFE-based: 30 features selected
Features: ['MSSubClass', 'LotFrontage', 'LotArea', 'Street', 'LandContour', 'Utilities', 'LandSlope', 'Condition1', 'Condition2', 'BldgType', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'RoofStyle', 'RoofMatl', 'Foundation', 'TotalBsmtSF', 'HeatingQC', 'FullBath', 'HalfBath', 'BedroomAbvGr', 'KitchenQual', 'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'GarageCars', 'GarageArea', 'WoodDeckSF', 'SaleCondition']

RFE systematically eliminates less important features, improving model performance and reducing overfitting. Thus we select 30 features